### ISSUE TITLE
Global design adjustments

### ISSUE THREAD

**Issue by amol-anand** [adobecom/firefly#10]
- [ ] Need to tweak the Global styles to match 
- [ ] CSS tweaks to make it look as close as possible the [homepage](https://firefly.adobe.com/)

Putting a laundry list of things but pick and fix what seems necessary
- [ ]  Section widths (we can stick to 375, 600, 900 and above but take a call to see what makes sense )
- [ ]  Navigation heights
- [ ]  Heading sizes
- [ ]  Margins
- [ ]  Custom Font Families
- [ ]  Font sizes
- [ ]  Colors
- [ ]  Buttons (primary, secondary)

**Comment by kunwarsaluja** [comment]
Marking this as closed for now. Will reopen incase it's needed later
