### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by amol-anand** [adobecom/firefly#4]
- [x] Style header (gnav from Milo) to look like https://firefly.adobe.com/
- [x] CSS tweaks to make it look as close as possible to header on [homepage](https://firefly.adobe.com/)
- [x] Check for other CSS styling elements missing from the header on live site

Once we know more if Milo team can make adjustments on gnav (or doc source) and if we can readily use the existing gnav, we'd have to :
- [x] CSS tweaks to make it look as close as possible to header on [homepage](https://firefly.adobe.com/)
- [x] Aligning below items to the right of the header
<img width="293" alt="image" src="https://github.com/adobecom/firefly/assets/53608019/d2316fc0-c5dc-453c-9db0-7c6f2eb7c6b3">

- [x] What's new tooltip

**Comment by kunwarsaluja** [comment]
assigning to @kailasnadh790 as he's already working on it

**Comment by kailasnadh790** [comment]
Deleted requiremnent:
- [ ] Create  a new custom header block for Firefly site, Take elements like login, app launcher etc. from the Milo Gnav and plug them in
