### ISSUE TITLE
[Navbar] Navbar items for unentitled user

### ISSUE THREAD

**Issue by tom-hightower** [adobecom/firefly#59]
- Users without enterprise entitlements should not see "Custom Models". 
- The "Community" item should be labeled "Gallery" for all users

Firefly site:
<img width="550" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/5da3b20f-f1a3-4dc2-b7e3-6f807d25447c">

Franklin:
<img width="573" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/6ebac1f3-4ed1-4e02-abd1-a98dde971849">

**Comment by kunwarsaluja** [comment]
this is related with #104

**Comment by kunwarsaluja** [comment]
Let close this and get it combined with #104 as the experience is 3 folds (all visitors, personal accounts, enterprise accounts). See #104 for more information
