### ISSUE TITLE
What's new block

### ISSUE THREAD

**Issue by amol-anand** [adobecom/firefly#6]
- [x] Create a block to showcase What's New Section
- [x] Tweak the Header to include the What's new Section
- [ ] First login, should popup the What's new Modal showcasing new things business wants to highlight

Maybe take an approach of making this a fragment for easy authorability and load it when and wherever it's needed

![Screenshot 2024-05-10 at 2 16 20 PM](https://github.com/adobecom/firefly/assets/10811320/69db1ceb-ed1c-43cc-97b9-f842ab76ee73)

**Comment by kunwarsaluja** [comment]
Closed with #36
