### ISSUE TITLE
[Hero] Hero image should fade between consecutive images

### ISSUE THREAD

**Issue by tom-hightower** [adobecom/firefly#60]
Hero image on franklin site jumps abruptly to next image

Firefly:
https://github.com/adobecom/firefly/assets/39915804/5cf18a2f-99cb-42cc-a02f-91e1bd9766c0

Franklin:
https://github.com/adobecom/firefly/assets/39915804/c70c64f6-b0bd-4b66-bb3a-b946b451790d

**Comment by kailasnadh790** [comment]
@tom-hightower this is fixed. Please review https://main--firefly--adobecom.hlx.live/.
