### ISSUE TITLE
[Hero] Typewriter prompt should show the cursor as it types/backspaces

### ISSUE THREAD

**Issue by tom-hightower** [adobecom/firefly#61]
Firefly:
<img width="496" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/216b2240-a5d5-4cec-ba24-1735fac9ced4">

Franklin:
<img width="496" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/462c4907-111a-4790-a07f-0428c810e99e">

**Comment by kailasnadh790** [comment]
@tom-hightower this is fixed. pls review https://main--firefly--adobecom.hlx.live/
