### ISSUE TITLE
[Hero] Artist name is hard to see on light backgrounds

### ISSUE THREAD

**Issue by tom-hightower** [adobecom/firefly#62]
The artist name in the lower right corner of the hero image is white, which makes it hard to discern on white/light colored hero images

<img width="398" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/ec35ba05-912b-41dd-8853-ee3f1780da20">

**Comment by kailasnadh790** [comment]
@tom-hightower , have put a darker background for author.
<img width="608" alt="image" src="https://github.com/adobecom/firefly/assets/53608019/92bfec45-75d2-4828-9a63-1999055bc417">
