### ISSUE TITLE
[Module Cards] Formatting for wide cards

### ISSUE THREAD

**Issue by tom-hightower** [adobecom/firefly#63]
Wide cards above the module carousel have incorrect formatting. They also need to be responsive as the screen size changes.

Firefly:
<img width="1697" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/81df15d4-35af-4d21-8800-acea2a1b03c8">

Franklin:
<img width="1697" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/5c48574d-febc-4ae5-9570-bd3c125801e2">

Firefly site responsiveness:

https://github.com/adobecom/firefly/assets/39915804/3b4bcdbb-96e4-4ebc-8c80-9ee8b106d3d3

**Comment by shsteimer** [comment]
Fixed by #89
