### ISSUE TITLE
[Module Cards] Font size and spacing for module carousel cards

### ISSUE THREAD

**Issue by tom-hightower** [adobecom/firefly#64]
Firefly:
<img width="740" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/5a8fb1c5-213b-418a-b838-9b8d38f2d503">

Franklin:
<img width="740" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/0c5f0abd-e360-4cf8-801a-400cb1ffd82e">

**Comment by kunwarsaluja** [comment]
@tom-hightower I think this is now fixed. Can you please confirm if https://main--firefly--adobecom.hlx.page/ to see if the cards-carousel spacing etc. are good for now.  As the DOM is changing, tried to make it as close as possible.

Reopen with specific changes needed incase of any concerns.
