### ISSUE TITLE
[Module Cards] Carousel should be horizontally scrollable

### ISSUE THREAD

**Issue by tom-hightower** [adobecom/firefly#66]
The module carousel should be scrollable via trackpad in addition to the next/prev buttons on either end

Firefly:

https://github.com/adobecom/firefly/assets/39915804/52233a94-1e84-475f-b05b-3982120a0583

**Comment by kunwarsaluja** [comment]
@tom-hightower I think this is now fixed. Can you please confirm if https://main--firefly--adobecom.hlx.page/ to see if the cards-carousel ae horizontally scrollable

Please reopen and let us know specific issues to be fixed.
