### ISSUE TITLE
[Gallery] Hover state

### ISSUE THREAD

**Issue by tom-hightower** [adobecom/firefly#67]
Hovering over an image in the gallery (in gallery tab or in homepage gallery) should have styling that matches current firefly site:
- Submitter profile pic / name
- Text size/weight
- Spacing
- Truncate long prompts
- Button styling

Firefly:
<img width="625" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/5d5dae80-b0bd-4650-8992-c05b6000927e">

Franklin:
<img width="625" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/45238fd1-bbbd-47d8-bc72-dc1af33399d3">

**Comment by kunwarsaluja** [comment]
@tom-hightower I think this is now fixed. Can you please check https://main--firefly--adobecom.hlx.page/ to see if this looks good.

Please reopen and let us know specific issues to be fixed.
