### ISSUE TITLE
[Gallery] Homepage gallery bottom text

### ISSUE THREAD

**Issue by tom-hightower** [adobecom/firefly#68]
Text above "View gallery" button should read "Visit gallery for more inspiration"

Firefly:
<img width="625" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/9e33ae46-f077-4af3-9fde-560430020669">

Franklin:
<img width="625" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/c9b30a20-1731-4516-977c-bf58c0dae0ac">

**Comment by kunwarsaluja** [comment]
Fixed : https://main--firefly--adobecom.hlx.live/
