### ISSUE TITLE
Login widget

### ISSUE THREAD

**Issue by amol-anand** [adobecom/firefly#8]
Use SUSI-light pop-up for login rather than the full page experience

There is no build process in Milo, however there are some options:
- Use microbundle locally and update the output file (e.g. https://github.com/adobecom/milo/blob/stage/package.json#L17)
- Use github actions to fetch a previously built file (e.g. https://github.com/adobecom/milo/blob/stage/.github/workflows/update-dependencies.yaml#L16)
- Manually update the file (e.g. https://github.com/adobecom/milo/commit/b344e44010c7f8c1c5d34b2d17756182edd07b78)

**Comment by amol-anand** [comment]
related to #75

**Comment by kunwarsaluja** [comment]
I think this can be closed, covered with #75 . Will reopen if needed later.
