### ISSUE TITLE
Localise header with i18n Keys

### ISSUE THREAD

**Issue by kunwarsaluja** [adobecom/firefly#81]
Localise header with i18n Keys

**Comment by kailasnadh790** [comment]
This done. Everything on https://adobe.sharepoint.com/:w:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7B6BA05CFE-C7AB-4DCE-B317-7290C9506CDC%7D&file=gnav.docx&action=default&mobileredirect=true&wdsle=0 is now replaced with i18 keys.
