### ISSUE TITLE
[UNIVERSAL NAV] Dark mode styling.

### ISSUE THREAD

**Issue by kailasnadh790** [adobecom/firefly#83]

**Comment by kailasnadh790** [comment]
@amol-anand do we need to do this ? or can be achieved with some configs ?

**Comment by kunwarsaluja** [comment]
@kailasnadh790 might need ask Unav team to see whats possible here or do we need to implement all styles ourselves ?

**Comment by kunwarsaluja** [comment]
@kailasnadh790 let's close this and cover all of it with review of dark mode and light mode styling in #109
