### ISSUE TITLE
[Module Cards] Module card config doesn't support hover animation + icon

### ISSUE THREAD

**Issue by tom-hightower** [adobecom/firefly#92]
When adding a hover animation url to a module card that has an icon, the icon no longer displays.
<img width="743" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/22c995f6-da0a-40e2-8f45-ed4cc52b0667">
<img width="623" alt="image" src="https://github.com/adobecom/firefly/assets/39915804/96e8a970-4aa0-4fd4-9635-902fedf2b0f3">

**Comment by kailasnadh790** [comment]
This is fixed. Please validate. @tom-hightower

**Comment by tom-hightower** [comment]
Looks good, thanks!
